/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <engine>
#include <fakemeta>
#include <dodx>
#include <dodfun>
#include <dodconst>
#include <dodstats>
#include <hamsandwich>
#include <fun>
#include <fakemeta_util>

#define PLUGIN "dod_zookarock"
#define VERSION "1.4"
#define AUTHOR "TONY"
#define ROCKETZUKA	100

#define OFFSET_WPN_ID			91
#define OFFSET_WPN_CLIP 		108
#define OFFSET_PISTOL_BPAMMO_LINUX	52
#define OFFSET_PISTOL_BPAMMO_WIN32	53
#define OFFSET_LINUX 			4
#define COUNTFLOTA 	0.2

#define FOV90 90
static zoom90 = 90

new g_mdlpnzrk[] = "models/w_pschreck_rocket.mdl"  // shell_pschreck
new g_mdlpiark[] = "models/w_piat_rocket.mdl" // shell_piat
new g_mdlbzkrk[] = "models/w_bazooka_rocket.mdl"// shell_bazooka 
new g_Explosion
new Float: fOrigin[3]
new wpnid




public plugin_precache(){
	g_Explosion = precache_model("sprites/explosion1.spr")
}
public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_clcmd("say /zuka", "testt")
	register_clcmd("say /t1", "test11") 
	register_clcmd("say /slot", "test12")
	register_clcmd("say /z", "testprone")
	register_clcmd("say /clip", "clipsetter")
	register_clcmd("say /anim", "animsetter")
	register_clcmd("say /zoomin", "zoominfov")
	register_clcmd("say /zoomout", "zoomoutfov")
	register_clcmd("say /baz", "sometestexplodes")
	
	
	// PZ is "shell_pschreck" 
	// 
	register_event( "23", "on_Explosion", "a", "1=3", "6=25" );     // SVC_TEMPENTITY
	
}

public testt(id)
{ 
	
	//////////baza find////////
	new G_rockclname[32]
	new Rent = engfunc(EngFunc_FindEntityByString, 0, "model", g_mdlpnzrk)
	
	new ptr = pev(Rent, pev_classname)
	new classname[32]
	
	
	new idOrigin[3] 
	pev (id, pev_origin, idOrigin)
	
	if(Rent>0){
	pev(Rent, pev_classname, ptr, G_rockclname, 31)
	client_print(id,print_chat,"classname - %s , Id %d", G_rockclname, Rent)
	set_pev(Rent, pev_movetype, MOVETYPE_NONE)

	// set_pev(Rent, pev_dmg, MOVETYPE_NONE)
	 
	
	new Float: RentOrigin[3]
	pev(Rent, pev_origin, RentOrigin)

	set_pev(Rent, pev_movetype, MOVETYPE_TOSS)
	set_pev(Rent, pev_velocity, {0.0 , 0.0, 0.0})
	/*  entity get string
	
	
	new size1[32], size2[32], size3[32], size4[32], size5[32], size6[32], size7[32], size8[32], size9[32]
	entity_get_string(Rent, 1, size1, 31);
	entity_get_string(Rent, 2, size2, 31);
	entity_get_string(Rent, 3, size3, 31);
	entity_get_string(Rent, 4, size4, 31);
	entity_get_string(Rent, 5, size5, 31);
	entity_get_string(Rent, 6, size6, 31);
	entity_get_string(Rent, 7, size7, 31);
	entity_get_string(Rent, 8, size8, 31);
	entity_get_string(Rent, 9, size9, 31);
	entity_get_string(Rent, 0, G_rockclname, 31);
	
	client_print(id,print_chat,"%s , %s , %s , %s , 5 = %s , %s  ,%s , %s , %s   ", G_rockclname,size1,size2,size3,size4,size5,size6,size7,size8, size9)
	/*
	
	/*
	/////////////////////////  CHANGE SPEED
	
	set_pev(Rent, pev_movetype, MOVETYPE_FLY)
	new Float:fVel[3]
	velocity_by_aim(id, ROCKETZUKA, fVel)	
	set_pev(Rent, pev_velocity, fVel)
	*/
	
	// updateexplo(Rent)
	// remove_entity(Rent)
	
}
	Rent = 0
	
} 

public test11(id){
	
	message_begin(MSG_BROADCAST, SVC_WEAPONANIM) /// ��������� ����� �������� V_weapon
	write_byte(4)
	write_byte(1)
	message_end()
}

public test12(id){
	
	dod_set_weaponlist(id, 10, 6, 2, 1); // ���������� ������ � ���� 1 
	// id weaponid, � ����� ����,  
	
}

public testprone(id){
		new pronestate =  dod_get_pronestate(id)
		client_print(id, print_center, "state is %d", pronestate)
}


stock dod_get_weapon_ent(id,wpnid)
{
	new ent = -1,entid

	new Float:origin[3]
	entity_get_vector(id,EV_VEC_origin,origin)
	
	while((ent = find_ent_in_sphere(ent,origin,0.4)) != 0)
			
		{
		if(is_valid_ent(ent))
			{
			entid = get_pdata_int(ent,OFFSET_WPN_ID,OFFSET_LINUX)
			
			if(wpnid == entid)
				return ent
			}
		}
		
	return 0
}

public clipsetter(id){
	
	
	// ��� ������ �� ������ ��������� ���� �� ����� � �������� ���������� ��� ��������.. ������������ �� ������ ����
	new clipg, ammog
	new wpnid = dod_get_user_weapon(id, clipg, ammog)
	new wpnent = dod_get_weapon_ent(id,wpnid)
	new clip = get_pdata_int(wpnent,OFFSET_WPN_CLIP,OFFSET_LINUX)

	client_print(id, print_center, "wpnid %d , wpent %d clip %d", wpnid, wpnent, clip )
	set_pdata_int(wpnent,OFFSET_WPN_CLIP,2,OFFSET_LINUX)
}

public animsetter(id){
	
	new clipg, ammog
	new wpnid = dod_get_user_weapon(id, clipg, ammog)
	new wpnent = dod_get_weapon_ent(id,wpnid)
	// new seqnum = get_pdata_int(id,91,OFFSET_LINUX) /// ����� ��������� ) 230 MAXSPEED
	new gisTeam[16]
	get_pdata_string(id, 1396, gisTeam, 16,1 ,4)
	client_print(id, print_center, "teams is %s", gisTeam)
	// set_pdata_int(id,365, 44, OFFSET_LINUX) // SET FOV 
	// set_pdata_int(id,522, 64, OFFSET_LINUX) // anim not played
	// set_pdata_int(wpnent,100, 1, OFFSET_LINUX) // anim not played
set_user_gravity(id, 3.0)

}
public zoominfov(id){
	
	if(zoom90>10){
	zoom90 = zoom90 - 1
	set_pdata_int(id,365, zoom90, OFFSET_LINUX)
	
	
}
}

public zoomoutfov(id){
	
	if(zoom90<100){
	zoom90 = zoom90 + 1
	set_pdata_int(id,365, zoom90, OFFSET_LINUX)
}
}



public dod_rocket_explosion(id, Float:fOrigin[3], wpnid) {
	
	client_print(id, print_chat, "ROCKIT")
	
	new iPlayers[32] //������� ������ ��� �������� �������� �������
	new iPlayer, iNum //��� ������ ���-�� ������� � ��������� ������ ������

	get_players(iPlayers, iNum, "ach") //�������� �������, �������� �������, ����� � hltv
	// on_Explosion(fOrigin)
}



	
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1049\\ f0\\ fs16 \n\\ par }
*/
